# Generated by Django 4.2 on 2023-05-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address_is_selected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('updated_at',)},
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
