# Generated by Django 4.2.3 on 2023-08-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_address_options_address_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-updated_at',)},
        ),
    ]
