# Generated by Django 4.2 on 2023-11-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Təsdiq olunmuş'),
        ),
    ]
