# Generated by Django 4.2 on 2023-11-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_customuser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_pending',
            field=models.BooleanField(default=True, help_text='İstifadəçi admin təsdiqini gözləyir?'),
        ),
    ]
