# Generated by Django 4.2 on 2023-11-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='just_registered',
            field=models.BooleanField(default=True),
        ),
    ]
