# Generated by Django 4.2 on 2023-11-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_customuser_just_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='VÖEN'),
        ),
    ]
