# Generated by Django 4.2 on 2023-11-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='conpany_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
