# Generated by Django 4.2 on 2023-11-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_customuser_conpany_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='conpany_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Şirkət adı'),
        ),
    ]
