# Generated by Django 4.2 on 2023-11-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_customuser_conpany_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='conpany_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Şirkətin adı'),
        ),
    ]
