# Generated by Django 4.2 on 2023-11-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_customuser_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='logo',
        ),
    ]
