# Generated by Django 4.2 on 2023-12-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_pendinguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Declined'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
