# Generated by Django 4.2 on 2023-12-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_customuser_is_approved_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
