# Generated by Django 4.2 on 2023-12-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='just_registered',
        ),
    ]
