# Generated by Django 4.2 on 2023-12-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_customuser_just_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='just_registered',
            field=models.BooleanField(default=True),
        ),
    ]
