# Generated by Django 4.2.3 on 2023-10-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('address_url', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('topbar_text', models.TextField()),
                ('copyright', models.CharField(max_length=256)),
                ('footer_payment_image', models.FileField(upload_to='')),
            ],
        ),
    ]
