# Generated by Django 4.2.3 on 2023-10-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='logo',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
    ]
