# Generated by Django 4.2.3 on 2023-10-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('icon', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='general',
            name='footer_description',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
