# Generated by Django 4.2 on 2023-04-30 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
