# Generated by Django 4.2 on 2023-05-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productprice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='red', max_length=256),
            preserve_default=False,
        ),
    ]
