# Generated by Django 4.2 on 2023-05-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort',)},
        ),
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
