# Generated by Django 4.2 on 2023-05-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_is_featured_alter_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
    ]
