# Generated by Django 4.2.3 on 2023-08-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_brand_country_brand_description_brand_website_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='website',
            new_name='importer',
        ),
    ]
