# Generated by Django 4.2.3 on 2023-10-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_featuredproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Çox Satılan Məhsul',
                'verbose_name_plural': 'Çox Satılan Məhsullar',
            },
        ),
    ]
