# Generated by Django 4.2 on 2023-11-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_customer_alter_order_ordered_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
