# Generated by Django 4.2 on 2023-12-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_wishlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
