# Generated by Django 4.2 on 2023-12-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_note_lastviewed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastViewed',
        ),
    ]
