# Generated by Django 4.2 on 2023-12-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_wishlist_product_alter_order_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
